package com.mycompany.metatraderbrokeradmin.Syncronization;

import javax.swing.BoxLayout;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kapilrohilla
 */
public class HistoryChartAndSymbolSyncronization extends javax.swing.JFrame {

    /**
     * Creates new form Sync_Common_Symbol
     */
    public HistoryChartAndSymbolSyncronization() {
//        initComponents();
        setTitle("CSV Upload");
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setVisible(true);
        this.setSize(800, 600);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
//        this.setSize(800,600);
        tabbedPane();
    }
    
    
    
    private void tabbedPane(){
        JTabbedPane tp=new JTabbedPane();  
        tp.setBounds(50,50,200,200);  
        CommonTabbedPanel common = new CommonTabbedPanel();
        SymbolTabbedPanel symbol = new SymbolTabbedPanel();
//        tp.add("Common",common);  
//        tp.add("Symbol",symbol);
        tp.add("CSV",new CSVUpload("csv"));
        
        Sync_Common_Symbol_Bottom bottomBtn = new Sync_Common_Symbol_Bottom();
        JSplitPane split = new JSplitPane(JSplitPane.VERTICAL_SPLIT, tp, bottomBtn);
        bottomBtn.setSize(500,20);
        add(split);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryChartAndSymbolSyncronization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryChartAndSymbolSyncronization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryChartAndSymbolSyncronization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryChartAndSymbolSyncronization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryChartAndSymbolSyncronization().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

//class Common extends javax.swing.JPanel{
//    Common(){
//        this.setSize(400,500);
//    }
//}

//class Symbol extends javax.swing.JPanel{
//    Symbol(){
//        this.setSize(400,500);
//    }
//}