/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.metatraderbrokeradmin;

import com.mycompany.metatraderbrokeradmin.Customer.temp;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kapilrohilla
 */
public class AllocationTable extends javax.swing.JPanel {

    /**
     * Creates new form AllocationTable
     */
    public AllocationTable() {
        initComponents();
        table();
    }
    
    final void table() {
        DefaultTableModel tablemodel = new DefaultTableModel();
        tablemodel.addColumn("Sno.");
        tablemodel.addColumn("Data Feeder");
        
        String rowData[][] = {
            {"1.", "PIP Feeder"},
            {"2.", "IQ Feeder"},
            {"3.", "MT5 Feeder"}
        };
        for (String[] rowData1 : rowData) {
            tablemodel.addRow(rowData1);
        }
        JTable table = new JTable(tablemodel);
        
        setLayout(new BorderLayout());
        
        table.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                int row = table.rowAtPoint(e.getPoint());
//                int column = table.columnAtPoint(e.getPoint());
//                Object selectedData = table.getValueAt(row, column);
                // Get the value of the clicked cell
//                Object value = table.getValueAt(row, column);
                if (e.getClickCount() == 2) {
                     int row = table.rowAtPoint(e.getPoint());
                    new DataFeedPopup(row).setVisible(true);
                }
            }
        });
        table.setEnabled(false);
        JScrollPane jsp = new JScrollPane(table);
        add(jsp, BorderLayout.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
