/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.metatraderbrokeradmin;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author techninza
 */
public class BottomPanel extends javax.swing.JPanel {

    /**
     * Creates new form BottomPanel
     */
    public BottomPanel() {
        initComponents();
        tab();
    }
    
    private void tab()
    {
        JTabbedPane tabbedPane = new JTabbedPane();

        // Create the tabs
        JPanel tab1 = new JPanel();
//        JButton b=new JButton("OK");
//        tab1.add(b,BorderLayout.SOUTH);
        tab1.add(new JLabel("Tab 1"));

        JPanel tab2 = new JPanel();
        tab2.add(new JLabel("Tab 2"));

        JPanel tab3 = new JPanel();
        tab3.add(new JLabel("Tab 3"));

        JournalPanel tab4 = new JournalPanel();
//        tab4.add(new JLabel("Tab 4"));

        // Add the tabs to the tabbed pane
        tabbedPane.addTab("News", tab1);
        tabbedPane.addTab("Calendar", tab2);
//        tabbedPane.addTab("Search", tab3);
        tabbedPane.addTab("Journal", tab4);
  setLayout(new BorderLayout());
        
        add(tabbedPane,BorderLayout.CENTER);
        // Add the tabbed pane to the frame
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
