/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.metatraderbrokeradmin;

import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kapilrohilla
 */
public class ChartInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChartInfoPanel
     */
    public ChartInfoPanel() {
//        initComponents();
        String column[] = {"Name", "Description"};
        String row[][] = {
            {"1 Minute History Chart", "Manage Price History provided in the form of 1 minute bars"},
            {"Bid/Ask/Last Ticks", "Manage Tick data of financial instruments"},
            {"Syncronization", "Syncronize data with other " + BrokerAdmin.APPNAME}
        };
        DefaultTableModel tableModel = new DefaultTableModel(row, column);
        JTable jt = new JTable(tableModel);
        jt.setEnabled(false);
        setLayout(new BorderLayout());

        jt.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
//                    JTable target = (JTable) e.getSource();
                    int row = jt.rowAtPoint(e.getPoint());
                    System.out.println("Row " + row + " clicked");
                    switch (row) {
                        case 0:
                            BrokerAdmin.splitPane.setRightComponent(new ChartPanel());
                            break;
                        case 1:
                            BrokerAdmin.splitPane.setRightComponent(new BidAskLastPanel());
                            break;
                        default:
                            BrokerAdmin.splitPane.setRightComponent(new SyncronizationPanel());
                            break;
                    }
                }
            }
        });
        JScrollPane overflow = new JScrollPane(jt);
        add(overflow, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
