/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.metatraderbrokeradmin;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import okhttp3.Call;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author techninza
 */
public class JournalPanel extends javax.swing.JPanel {

    /**
     * Creates new form JournalPanel
     */

    
    public JournalPanel() {
        initComponents();
        try{
        tabledata();
        }
        catch(Exception e)
        {
            
        }
    }
    
    private String getData() {
        OkHttpClient client = new OkHttpClient();
        String url = "http://65.0.59.137:8080/journal";
        // Create a Request object
        Request request = new Request.Builder()
                .url(url)
                .build();
        Call call = client.newCall(request);
        try {
            Response res = call.execute();
            return res.body().string();
        } catch (IOException e) {
            System.out.println("API Error");
            return "";
        }
    }

    private void tabledata() throws JSONException {
        String apiData = getData();
        JSONObject jsonob=new JSONObject(apiData);
        JSONArray js = jsonob.getJSONArray("message");
        ArrayList<JSONObject> arraylist = new ArrayList<>();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Time");
        tableModel.addColumn("Server");
        tableModel.addColumn("Message");
     
        for (int i = 0; i < js.length(); i++) {
            JSONObject jso = js.getJSONObject(i);
            String server = jso.getString("server");
            String text = jso.getString("text");
            String created = jso.getString("createdAt");
        
            String rowData[] = {created, server, text};
            arraylist.add(jso);
            tableModel.addRow(rowData);
        }

        //JTable jTable1 = new JTable(tableModel);
        JTable jt = new JTable(tableModel);
     
     
        jt.setEnabled(false);
        setLayout(new BorderLayout());
        JScrollPane scrollPane = new JScrollPane(jt);
        add(scrollPane, BorderLayout.CENTER);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
