/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.metatraderbrokeradmin.GroupConfig;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Lenovo
 */
public class GroupTradeMarginRates extends javax.swing.JPanel {

    /**
     * Creates new form GroupTradeMarginRates
     */
    public GroupTradeMarginRates() {
        initComponents();
//        jCheckBox1.setSelected(true);
//        jTextField1.setEnabled(false);
//        jTextField2.setEnabled(false);
//        jTable1.setEnabled(false);

//        jCheckBox1.addItemListener(new ItemListener() {
//            @Override
//            public void itemStateChanged(ItemEvent e) {
//                if (e.getStateChange() == ItemEvent.SELECTED) {
//                    jTextField1.setEnabled(false);
//                    jTextField2.setEnabled(false);
//                    jTable1.setEnabled(false);
//                } else {
//                    jTextField1.setEnabled(true);
//                    jTextField2.setEnabled(true);
//                    jTable1.setEnabled(true);
//                }
//            }
//        });
    }

//    public JCheckBox getjCheckBox1() {
//        return jCheckBox1;
//    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }
    
    String getJSONData(String key, JSONObject jso){
        try{
            String data = jso.getString(key);
            return data;
        }catch(Exception ex){
            ex.getStackTrace();
            return "nf";
        }
    }
      public GroupTradeMarginRates(JSONObject jso) {
        initComponents();
//        jCheckBox1.setSelected(true);
//        jTextField1.setEnabled(false);
//        jTextField2.setEnabled(false);
//        jTable1.setEnabled(false);
        try{
            String liqMargin = getJSONData("MarginLiquidity", jso);
            String currencyMarginRates = getJSONData("MarginCurrency", jso);
            boolean useDefaultMr = jso.getBoolean("useDefaultMr");
            
            jTextField1.setText(liqMargin);
            jTextField2.setText(currencyMarginRates);
//            jCheckBox1.setSelected(useDefaultMr);
            
            JSONArray marginRatesTableData = jso.getJSONArray("MarginRatesTable");
            
        }catch(JSONException ex){
            ex.getStackTrace();
        }
//        jCheckBox1.addItemListener(new ItemListener() {
//            @Override
//            public void itemStateChanged(ItemEvent e) {
//                if (e.getStateChange() == ItemEvent.SELECTED) {
//                    jTextField1.setEnabled(false);
//                    jTextField2.setEnabled(false);
//                    jTable1.setEnabled(false);
//                } else {
//                    jTextField1.setEnabled(true);
//                    jTextField2.setEnabled(true);
//                    jTable1.setEnabled(true);
//                }
//            }
//        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Please specify margin rates for different types of trade operations.");

        jLabel2.setText("Liquidity Margin Rate : ");

        jLabel3.setText("Currency Margin Rate : ");

        jLabel4.setText("Margin Rates");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Initial Margin", null, null, null, null},
                {"Buy", "1.00000", "0.0", "0.0", "0.0"},
                {"Sell", "1.00000", "0.0", "0.0", "0.0"},
                {"Maintenance Margin", null, null, null, null},
                {"Buy", "0.00000", "0.0", "0.0", "0.0"},
                {"Sell", "0.00000", "0.0", "0.0", "0.0"},
                {"", null, null, null, null}
            },
            new String [] {
                "", "Market Order", "Limit Order", "Stop Order", "Stop Limit Order"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
