/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.metatraderbrokeradmin.GroupConfig;

import com.mycompany.metatraderbrokeradmin.SymbolConfig.SixTabFrame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author techninza
 */
public class SymbolsGroupConfig extends javax.swing.JPanel {

    public static JSONArray symbolsTableData = new JSONArray();
    public static JSONArray symbolTableData2 = new JSONArray();
    JSONArray userDataList;
    int selectedIndex = -1;
    // previousl arr

    public static DefaultTableModel model;

    public SymbolsGroupConfig() {
        initComponents();
        model = new DefaultTableModel();
        model.addColumn("Symbol");
        model.addColumn("Spread");
        model.addColumn("Trade");

        jTable1.setModel(model);
    }

    public SymbolsGroupConfig(JSONArray js, Boolean isUpdate) {
        initComponents();
        model = new DefaultTableModel();
        this.userDataList = js;
        model.addColumn("Symbol");
        model.addColumn("Spread");
        model.addColumn("Trade");

        symbolsTableData = js;
        for (int i = 0; i < js.length(); i++) {
            JSONObject jso = js.getJSONObject(i);
            try {
                String sym = jso.getString("Symbol");
                Vector<String> vec = new Vector<>();
                vec.add(sym);
                model.addRow(vec);
            } catch (JSONException ex) {
                System.out.println(ex.getMessage());
            }

        }
//        System.out.println("symbolData4table: ");
//        System.out.println("jsa: " + js.getJSONObject(0));
//        try {
////            model.addRow(symbolsTableData.get(0));
//            System.out.println("Symbol data" + js.toString());
//            for (int i = 0; i < js.length(); i++) {
//                JSONObject jsa = js.getJSONObject(i);
//                String symbol = jsa.getString("Symbol");
//                String x[] = {symbol, "", ""};
//                model.addRow(x);
//            }
//        } catch (JSONException ex) {
//            System.out.println("ele ot found");
//        }

        jTable1.setModel(model);

        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    selectedIndex = jTable1.rowAtPoint(e.getPoint());
                    jButton2.setVisible(true);
                }
            }
        });

//        jTable1.setEnabled(false);
        jButton2.setVisible(false);

//        jButton1.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                new AddNewSymbol();
//            }
//        });
    }

    public JTable getjTable1() {
        return jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Please set up Individuals Parameters for Symbol Trade for the Group.");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"MARKET WATCH FOREX EURTRY", "Default", "Default"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Symbol", "Spread", "Trade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(48, 48, 48)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new AddNewSymbol();
//        new SixTabFrame("Invalid").setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        symbolsTableData.remove(selectedIndex);
        
        symbolTableData2.clear();
//        JSONObject newJSON = new JSONObject();
//        newJSON.
//           for(int i=0; i<symbolsTableData.length(); i++){
//               JSONObject jso =  symbolsTableData.getJSONObject(selectedIndex);
//               if(s)
//           }
//        symbolsTableData.remove(selectedIndex);
        model.removeRow(selectedIndex);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        System.out.println("edit btn clicked");
        // new AddNewSymbol(symbolsTableData.get(selectedIndex), selectedIndex).setVisible(true);
//        new AddNewSymbol().setVisible(true);
//        new SixTabFrame("Invalid").setVisible(true);
        JSONObject js = userDataList.getJSONObject(selectedIndex);
        new AddNewSymbol(js);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
